version : '3'
 
services:
  ### Setup the APIs
  peopleapi:
    image: peopleapi
    ports:
      - 8082:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8080
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - JAEGER_SERVICE_NAME=peopleapi
    networks:
      - dotnetcorepromgrafanajaeger

  locationsapi:
    image: locationsapi
    ports:
      - 8084:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8080
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - JAEGER_SERVICE_NAME=locationsapi
    networks:
      - dotnetcorepromgrafanajaeger

  ### Setup the Monitoring
  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - prometheus-data-volume:/prometheus # persist the data
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - dotnetcorepromgrafanajaeger

  grafana: 
    image: grafana/grafana
    #command:
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=P@ssw0rd
    restart: always
    ports:
      - 3000:3000
    volumes:
      - grafana-data-volume:/var/lib/grafana # persist the data
    networks:
      - dotnetcorepromgrafanajaeger
  
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5778:5778/tcp"
      - "6831:6831/udp"
      - "16686:16686"
      - "16687:16687" # Query Service and UI Metrics
      - "14271:14271" # Agent Metrics
    networks:
      - dotnetcorepromgrafanajaeger

### put all the networks here
networks:
  dotnetcorepromgrafanajaeger:

### put all the volume listings here for persistent data
volumes:
  prometheus-data-volume:
  grafana-data-volume:
